# Generated by Django 4.1.7 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
