# Generated by Django 4.1.7 on 2024-03-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_usuario_fecha_creacion_usuarioefimero_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
