# Generated by Django 4.1.7 on 2024-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioefimero',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='fotos_incognito/'),
        ),
    ]
