# Generated by Django 4.1.7 on 2024-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='especialista/')),
                ('publicacion', models.CharField(max_length=400)),
                ('datos', models.CharField(max_length=100)),
            ],
        ),
    ]
