# Generated by Django 4.1.7 on 2024-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_especialista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='datos',
        ),
        migrations.AddField(
            model_name='especialista',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especialista',
            name='celular',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especialista',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='especialista',
            name='enlace_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='enlace_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='enlace_tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='publicacion',
            field=models.CharField(default='', max_length=400),
        ),
    ]
