# Generated by Django 4.1.7 on 2024-03-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_publicacionefimero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='foto',
        ),
    ]
