# Generated by Django 4.1.7 on 2024-03-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_especialista_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
