# Generated by Django 4.1.7 on 2024-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_especialista_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='enlace_facebook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='enlace_instagram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='enlace_linkedin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='enlace_tiktok',
            field=models.CharField(default='', max_length=50),
        ),
    ]
