# Generated by Django 4.1.7 on 2024-03-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_especialista_enlace_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='enlace_facebook',
            new_name='nombre_facebook',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='enlace_instagram',
            new_name='nombre_instagram',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='enlace_linkedin',
            new_name='nombre_linkedin',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='enlace_tiktok',
            new_name='nombre_tiktok',
        ),
    ]
